import type { Metadata } from "next";
import { Inter } from "next/font/google";
import type React from "react";
import SiteFooter from "@/components/site-footer";
import SiteHeader from "@/components/site-header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Design Tool Landing Page",
  description: "Generated by create next app",
  openGraph: {
    type: "website",
    title: "Design Tool Landing Page",
    description:
      "A sleek, dark-mode landing page built with Next.js 15, Tailwind CSS, Framer Motion & Shadcn UI. Built by Moussa.",
    images: [
      {
        url: "https://design-tool-lp.vercel.app/preview.png",
        width: 1200,
        height: 630,
        alt: "Design Tool Landing Page",
        type: "image/png",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${inter.className} antialiased relative`}>
        {/* Global Background Video */}
        <div className="fixed inset-0 z-[-1]">
          <video
            autoPlay
            loop
            muted
            playsInline
            className="h-full w-full object-cover"
          >
            <source src="/batik-view.mp4" type="video/mp4" />
            Your browser does not support the video tag.
          </video>
          {/* Glassmorphism Overlay */}
          <div className="absolute " />
        </div>
        <div className="flex min-h-screen flex-col">
          <SiteHeader />
          {children}
          <SiteFooter />
        </div>
      </body>
    </html>
  );
}
